# Generated by Django 2.2.5 on 2019-09-15 14:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SW',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('picture_path', models.CharField(max_length=200)),
                ('MC_path', models.CharField(max_length=200)),
                ('birthDate', models.DateTimeField(verbose_name='date birth')),
                ('description', models.CharField(max_length=500)),
                ('third_email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=400)),
                ('price', models.IntegerField()),
                ('sw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sw.SW')),
            ],
        ),
    ]
