# Generated by Django 2.2.5 on 2019-09-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sw', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sw',
            old_name='description',
            new_name='about',
        ),
        migrations.AddField(
            model_name='sw',
            name='heigth',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sw',
            name='weigth',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
