# Generated by Django 2.2.5 on 2019-09-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_sw', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sw',
            name='eye_color',
        ),
        migrations.RemoveField(
            model_name='sw',
            name='status',
        ),
        migrations.AddField(
            model_name='sw',
            name='description',
            field=models.CharField(default='description', max_length=500),
            preserve_default=False,
        ),
    ]
