# Generated by Django 2.2.5 on 2019-09-12 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_client', '0001_initial'),
        ('app_sw', '0002_auto_20190912_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(verbose_name='start time')),
                ('end', models.DateTimeField(verbose_name='end time')),
                ('place', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=20)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_client.Client')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_sw.Service')),
            ],
        ),
    ]
