# Generated by Django 2.2.5 on 2019-09-15 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_sw', '0001_initial'),
        ('app_date', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app_sw.Service'),
        ),
    ]
